apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: reversewords-finance-app
  namespace: gitops-apps
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - reversewords-finance-app
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: reversewords-finance-app-subscription
  namespace: gitops-apps
  labels:
    app: reversewords-finance-app
  annotations:
    apps.open-cluster-management.io/git-path: apps/reversewords/
    apps.open-cluster-management.io/git-branch: stage
spec:
  channel: gitops-apps/acm-gitops-github
  placement:
    placementRef:
      kind: PlacementRule
      name: finance-dev-clusters
